version: '3.11'

services:
  morpho:
    image: diable201/morphoimage:latest
    container_name: morpho
    environment:
      - OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN
      - MONGO_LINK
      - MONGO_DB
      - TEMPERATURE
      - ALLOWED_USERS
    restart: always
    logging:
      driver: local